ide.workspace=/home/steve/video_streaming_10g_demo_v1.4.1_2026.1_imx900_rpi/fpga/Ti375N1156-DK/embedded_sw/sapphire_gen
ide.bsp=/home/steve/video_streaming_10g_demo_v1.4.1_2026.1_imx900_rpi/fpga/Ti375N1156-DK/embedded_sw/sapphire_gen/bsp
