
// Efinity Top-level template
// Version: 2026.1.132.4.5
// Date: 2026-10-03 18:55

// Copyright (C) 2013 - 2026 Efinix Inc. All rights reserved.

// This file may be used as a starting point for Efinity synthesis top-level target.
// The port list here matches what is expected by Efinity constraint files generated
// by the Efinity Interface Designer.

// To use this:
//     #1)  Save this file with a different name to a different directory, where source files are kept.
//              Example: you may wish to save as videostream.v
//     #2)  Add the newly saved file into Efinity project as design file
//     #3)  Edit the top level entity in Efinity project to:  videostream
//     #4)  Insert design content.


module videostream
(
  (* syn_peri_port = 0 *) input cam_scl_IN,
  (* syn_peri_port = 0 *) input cam_sda_IN,
  (* syn_peri_port = 0 *) input ddr0_refclk,
  (* syn_peri_port = 0 *) input [1:0] sw,
  (* syn_peri_port = 0 *) input uart_rxd,
  (* syn_peri_port = 0 *) input pll_locked,
  (* syn_peri_port = 0 *) input pll_inst2_LOCKED,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_CONTENTION_LP0,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_CONTENTION_LP1,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_CONTROL_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_CONTROL_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_ESC_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_ESC_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_SOT_HS_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_SOT_HS_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_SOT_SYNC_HS_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_ERR_SOT_SYNC_HS_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_LP_CLK,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ACTIVE_HS_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ACTIVE_HS_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_CLK_ACTIVE_HS,
  (* syn_peri_port = 0 *) input [7:0] dphy_rx1_RX_DATA_ESC,
  (* syn_peri_port = 0 *) input [15:0] dphy_rx1_RX_DATA_HS_LAN0,
  (* syn_peri_port = 0 *) input [15:0] dphy_rx1_RX_DATA_HS_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_LPDT_ESC,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_SKEW_CAL_HS_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_SKEW_CAL_HS_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_SYNC_HS_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_SYNC_HS_LAN1,
  (* syn_peri_port = 0 *) input [3:0] dphy_rx1_RX_TRIGGER_ESC,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ULPS_ACTIVE_CLK_NOT,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ULPS_ACTIVE_NOT_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ULPS_ACTIVE_NOT_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ULPS_CLK_NOT,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ULPS_ESC_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_ULPS_ESC_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_VALID_ESC,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_VALID_HS_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_RX_VALID_HS_LAN1,
  (* syn_peri_port = 0 *) input dphy_rx1_STOPSTATE_CLK,
  (* syn_peri_port = 0 *) input dphy_rx1_STOPSTATE_LAN0,
  (* syn_peri_port = 0 *) input dphy_rx1_STOPSTATE_LAN1,
  (* syn_peri_port = 0 *) input osc_inst1_CLKOUT,
  (* syn_peri_port = 0 *) input pll_inst2_CLKOUT0,
  (* syn_peri_port = 0 *) input sfp0_iface_clk,
  (* syn_peri_port = 0 *) input dphy_rx1_SLOWCLK,
  (* syn_peri_port = 0 *) input pll_inst1_CLKOUT0,
  (* syn_peri_port = 0 *) input clk_100m,
  (* syn_peri_port = 0 *) input jtag_inst1_CAPTURE,
  (* syn_peri_port = 0 *) input jtag_inst1_DRCK,
  (* syn_peri_port = 0 *) input jtag_inst1_RESET,
  (* syn_peri_port = 0 *) input jtag_inst1_RUNTEST,
  (* syn_peri_port = 0 *) input jtag_inst1_SEL,
  (* syn_peri_port = 0 *) input jtag_inst1_SHIFT,
  (* syn_peri_port = 0 *) input jtag_inst1_TCK,
  (* syn_peri_port = 0 *) input jtag_inst1_TDI,
  (* syn_peri_port = 0 *) input jtag_inst1_TMS,
  (* syn_peri_port = 0 *) input jtag_inst1_UPDATE,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_CAPTURE__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_DRCK__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_RESET__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_RUNTEST__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_SEL__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_SHIFT__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_TCK__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_TDI__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_TMS__,
  (* syn_peri_port = 0 *) input jtag_inst2_autodbg_UPDATE__,
  (* syn_peri_port = 0 *) input ddr_ARREADY_0,
  (* syn_peri_port = 0 *) input ddr_AWREADY_0,
  (* syn_peri_port = 0 *) input [5:0] ddr_BID_0,
  (* syn_peri_port = 0 *) input [1:0] ddr_BRESP_0,
  (* syn_peri_port = 0 *) input ddr_BVALID_0,
  (* syn_peri_port = 0 *) input cfg_done,
  (* syn_peri_port = 0 *) input ddr_CTRL_BUSY,
  (* syn_peri_port = 0 *) input [1:0] ddr_CTRL_CKE,
  (* syn_peri_port = 0 *) input ddr_CTRL_CMD_Q_ALMOST_FULL,
  (* syn_peri_port = 0 *) input ddr_CTRL_DP_IDLE,
  (* syn_peri_port = 0 *) input ddr_CTRL_INT,
  (* syn_peri_port = 0 *) input ddr_CTRL_MEM_RST_VALID,
  (* syn_peri_port = 0 *) input [1:0] ddr_CTRL_PORT_BUSY,
  (* syn_peri_port = 0 *) input ddr_CTRL_REFRESH,
  (* syn_peri_port = 0 *) input [511:0] ddr_RDATA_0,
  (* syn_peri_port = 0 *) input [5:0] ddr_RID_0,
  (* syn_peri_port = 0 *) input ddr_RLAST_0,
  (* syn_peri_port = 0 *) input [1:0] ddr_RRESP_0,
  (* syn_peri_port = 0 *) input ddr_RVALID_0,
  (* syn_peri_port = 0 *) input ddr_WREADY_0,
  (* syn_peri_port = 0 *) input gpio_inst1,
  (* syn_peri_port = 0 *) input system_spi_0_io_data_0_read,
  (* syn_peri_port = 0 *) input system_spi_0_io_data_1_read,
  (* syn_peri_port = 0 *) input [31:0] cmn_inst1_USER_APB_PRDATA,
  (* syn_peri_port = 0 *) input [63:0] sfp0_RXD,
  (* syn_peri_port = 0 *) input sfp0_BLOCK_LOCK,
  (* syn_peri_port = 0 *) input sfp0_HI_BER,
  (* syn_peri_port = 0 *) input cmn_inst1_PMA_CMN_READY,
  (* syn_peri_port = 0 *) input sfp0_IRQ,
  (* syn_peri_port = 0 *) input [7:0] sfp0_RXC,
  (* syn_peri_port = 0 *) input [3:0] sfp0_PMA_XCVR_POWER_STATE_ACK,
  (* syn_peri_port = 0 *) input cmn_inst1_USER_APB_PREADY,
  (* syn_peri_port = 0 *) input sfp0_PCS_STATUS,
  (* syn_peri_port = 0 *) input sfp0_PHY_INTERRUPT,
  (* syn_peri_port = 0 *) input sfp0_PMA_RX_SIGNAL_DETECT,
  (* syn_peri_port = 0 *) input sfp0_PMA_XCVR_PLLCLK_EN_ACK,
  (* syn_peri_port = 0 *) output cam_en,
  (* syn_peri_port = 0 *) output cam_scl_OUT,
  (* syn_peri_port = 0 *) output cam_scl_OE,
  (* syn_peri_port = 0 *) output cam_sda_OUT,
  (* syn_peri_port = 0 *) output cam_sda_OE,
  (* syn_peri_port = 0 *) output [5:0] led,
  (* syn_peri_port = 0 *) output scl_debug,
  (* syn_peri_port = 0 *) output sda_debug,
  (* syn_peri_port = 0 *) output uart_txd,
  (* syn_peri_port = 0 *) output dphy_rx1_FORCE_RX_MODE,
  (* syn_peri_port = 0 *) output dphy_rx1_RESET_N,
  (* syn_peri_port = 0 *) output dphy_rx1_RST0_N,
  (* syn_peri_port = 0 *) output jtag_inst1_TDO,
  (* syn_peri_port = 0 *) output jtag_inst2_autodbg_TDO__,
  (* syn_peri_port = 0 *) output [32:0] ddr_ARADDR_0,
  (* syn_peri_port = 0 *) output ddr_ARAPCMD_0,
  (* syn_peri_port = 0 *) output [1:0] ddr_ARBURST_0,
  (* syn_peri_port = 0 *) output [5:0] ddr_ARID_0,
  (* syn_peri_port = 0 *) output [7:0] ddr_ARLEN_0,
  (* syn_peri_port = 0 *) output ddr_ARLOCK_0,
  (* syn_peri_port = 0 *) output ddr_ARQOS_0,
  (* syn_peri_port = 0 *) output [2:0] ddr_ARSIZE_0,
  (* syn_peri_port = 0 *) output ddr_ARSTN_0,
  (* syn_peri_port = 0 *) output ddr_ARVALID_0,
  (* syn_peri_port = 0 *) output [32:0] ddr_AWADDR_0,
  (* syn_peri_port = 0 *) output ddr_AWALLSTRB_0,
  (* syn_peri_port = 0 *) output ddr_AWAPCMD_0,
  (* syn_peri_port = 0 *) output [1:0] ddr_AWBURST_0,
  (* syn_peri_port = 0 *) output [3:0] ddr_AWCACHE_0,
  (* syn_peri_port = 0 *) output ddr_AWCOBUF_0,
  (* syn_peri_port = 0 *) output [5:0] ddr_AWID_0,
  (* syn_peri_port = 0 *) output [7:0] ddr_AWLEN_0,
  (* syn_peri_port = 0 *) output ddr_AWLOCK_0,
  (* syn_peri_port = 0 *) output ddr_AWQOS_0,
  (* syn_peri_port = 0 *) output [2:0] ddr_AWSIZE_0,
  (* syn_peri_port = 0 *) output ddr_AWVALID_0,
  (* syn_peri_port = 0 *) output ddr_BREADY_0,
  (* syn_peri_port = 0 *) output cfg_reset,
  (* syn_peri_port = 0 *) output cfg_sel,
  (* syn_peri_port = 0 *) output cfg_start,
  (* syn_peri_port = 0 *) output ddr_RREADY_0,
  (* syn_peri_port = 0 *) output [511:0] ddr_WDATA_0,
  (* syn_peri_port = 0 *) output ddr_WLAST_0,
  (* syn_peri_port = 0 *) output [63:0] ddr_WSTRB_0,
  (* syn_peri_port = 0 *) output ddr_WVALID_0,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_0_write,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_0_writeEnable,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_1_write,
  (* syn_peri_port = 0 *) output system_spi_0_io_data_1_writeEnable,
  (* syn_peri_port = 0 *) output system_spi_0_io_sclk_write,
  (* syn_peri_port = 0 *) output system_spi_0_io_ss,
  (* syn_peri_port = 0 *) output [23:0] cmn_inst1_USER_APB_PADDR,
  (* syn_peri_port = 0 *) output sfp0_PCS_RST_N_TX,
  (* syn_peri_port = 0 *) output [63:0] sfp0_TXD,
  (* syn_peri_port = 0 *) output [31:0] cmn_inst1_USER_APB_PWDATA,
  (* syn_peri_port = 0 *) output [7:0] sfp0_TXC,
  (* syn_peri_port = 0 *) output cmn_inst1_USER_APB_PENABLE,
  (* syn_peri_port = 0 *) output sfp0_PHY_RESET_N,
  (* syn_peri_port = 0 *) output sfp0_PMA_TX_ELEC_IDLE,
  (* syn_peri_port = 0 *) output cmn_inst1_USER_APB_PSEL,
  (* syn_peri_port = 0 *) output [3:0] sfp0_PMA_XCVR_POWER_STATE_REQ,
  (* syn_peri_port = 0 *) output cmn_inst1_USER_APB_PWRITE,
  (* syn_peri_port = 0 *) output sfp0_ETH_EEE_ALERT_EN,
  (* syn_peri_port = 0 *) output sfp0_PCS_RST_N_RX,
  (* syn_peri_port = 0 *) output sfp0_PMA_XCVR_PLLCLK_EN
);


endmodule

